/* ==========================================================================
   chunks.js — the streaming world.

   Nothing exists until it is close enough to matter, and it stops existing the
   moment it is not. The island is cut into 64 m tiles; about thirty are ever
   resident out of the two hundred and fifty odd it contains.

   Three things make this possible, and all three are properties the world
   already had for other reasons:

     1. heightAt(x,z) and climateAt(x,z) are PURE FUNCTIONS OF POSITION. No
        global state, no accumulation. A tile can therefore be generated,
        destroyed, and regenerated byte-identical later.
     2. Every tile seeds its RNG from (seed, tileX, tileZ). This is not a
        nicety — without it the world reshuffles itself as you walk, and trees
        move when you look away.
     3. The far field (terrain.js) keeps a single coarse mesh of the whole
        island resident, so streaming never makes the world end at the edge of
        the ring. The summit still sees everything.

   The costs this is designed around:

     · Building a tile is expensive, so it is a STATE MACHINE driven by a queue
       with a per-frame time budget. A frame never builds more than it can pay
       for, so streaming cannot hitch.
     · Heights are computed ONCE per tile and reused by the mesh, the flora and
       the props. Placement used to call heightAt fresh for every candidate,
       and normalAt cost four more on top of that.
     · Thin instances belong to a mesh, so per-tile instancing would duplicate
       tree geometry hundreds of times. Instead there is ONE mesh per species
       and each tile owns a compact slice of matrices; the species buffer is
       repacked from the resident tiles whenever the resident set changes.
     · Typed arrays are pooled. Tiles churn constantly, and allocating fresh
       buffers each time would cause exactly the GC stutter that streaming is
       supposed to prevent.
   ========================================================================== */
import { makeRNG, makeNoise2D, clamp, lerp, smoothstep } from './noise.js';
import { WORLD, buildTerrainTile, buildFarField, makeGroundMaterial, makeFarMaterial } from './terrain.js';
import { SPECIES, speciesMesh, tuftMesh, grassMaterial } from './flora.js';
import { createColliders } from './collide.js';

/* ==========================================================================
   Buffer pool
   ========================================================================== */

function createPool(opts) {
  opts = opts || {};
  const CAP = opts.capBytes || 24 * 1024 * 1024;   // the pool itself is bounded
  const bins = new Map();
  let pooled = 0;
  let taken = 0, recycled = 0;

  return {
    take(n) {
      taken++;
      const bin = bins.get(n);
      if (bin && bin.length) {
        recycled++;
        pooled -= n * 4;
        const a = bin.pop();
        a.fill(0);
        return a;
      }
      return new Float32Array(n);
    },
    give(a) {
      if (!a || !(a instanceof Float32Array)) return;
      const bytes = a.length * 4;
      if (pooled + bytes > CAP) return;              // let GC have it instead
      let bin = bins.get(a.length);
      if (!bin) { bin = []; bins.set(a.length, bin); }
      if (bin.length >= 64) return;
      bin.push(a);
      pooled += bytes;
    },
    clear() { bins.clear(); pooled = 0; },
    stats() { return { pooledBytes: pooled, bins: bins.size, taken, recycled }; },
  };
}

/* ==========================================================================
   Per-tile placement

   Same rejection sampling as before, but against a tile's cached height grid
   rather than the analytic field, and seeded from the tile so it is repeatable.
   ========================================================================== */

function tileScatter(field, tile, rng, n, o) {
  const out = [];
  const { x0, z0, size } = tile;
  const { heights, NA, step } = tile;
  let tries = 0;
  const maxTries = n * (o.effort || 14);

  // bilinear read of the cached height grid — the apron means the edges are
  // real samples, not clamped guesses
  const h = (x, z) => {
    const fx = (x - x0) / step + 1, fz = (z - z0) / step + 1;
    const i = Math.floor(fx), j = Math.floor(fz);
    if (i < 0 || j < 0 || i >= NA - 1 || j >= NA - 1) return field.heightAt(x, z);
    const tx = fx - i, tz = fz - j;
    const a = heights[j * NA + i], b = heights[j * NA + i + 1];
    const c = heights[(j + 1) * NA + i], d = heights[(j + 1) * NA + i + 1];
    return lerp(lerp(a, b, tx), lerp(c, d, tx), tz);
  };

  while (out.length < n && tries++ < maxTries) {
    const x = x0 + rng() * size;
    const z = z0 + rng() * size;
    const y = h(x, z);
    if (y < (o.minY == null ? 0.6 : o.minY) || y > (o.maxY == null ? 999 : o.maxY)) continue;
    if (field.lake && field.lakeT(x, z) < 1.02 && y < field.lakeLevel + 0.15) continue;

    const moist = field.moistureAt(x, z);
    const w = field.climate.climateAt(x, z, y, field.inlandOf(x, z), moist);
    const p = o.pick(w, y, 0, moist);
    if (p <= 0 || rng() > p) continue;

    // slope from the cache: two reads, not four heightAt calls
    const e = Math.max(step, 1.2);
    const nx = (h(x - e, z) - h(x + e, z)) / (2 * e);
    const nz = (h(x, z - e) - h(x, z + e)) / (2 * e);
    const ny = 1 / Math.hypot(nx, 1, nz);
    const slope = 1 - clamp(ny, 0, 1);
    if (slope > (o.maxSlope == null ? 0.5 : o.maxSlope)) continue;

    out.push({ x, y, z, slope, moist, w });
  }
  return out;
}

/* ==========================================================================
   The manager
   ========================================================================== */

export function createChunkManager(BABYLON, scene, field, shaders, opts) {
  opts = opts || {};
  const TILE = opts.tile || 64;
  const pool = createPool();

  const rings = {
    near: opts.nearRings == null ? 2 : opts.nearRings,
    mid: opts.midRings == null ? 5 : opts.midRings,
  };
  const density = { near: 1, mid: opts.midDensity == null ? 0.35 : opts.midDensity };
  let grassScale = opts.grassScale == null ? 1 : opts.grassScale;
  let floraScale = opts.floraScale == null ? 1 : opts.floraScale;

  const groundMat = makeGroundMaterial(BABYLON, scene, shaders);
  const farMaterial = makeFarMaterial(BABYLON, scene, shaders);
  const far = buildFarField(BABYLON, scene, field, farMaterial,
    { segments: opts.farSegments || 128, drop: 0 });

  /* The cut follows the ring: the far field starts exactly where the streamed
     tiles stop, and moves when quality changes the ring size. */
  function syncFarCut() {
    // a little inside the ring edge, so a half-built tile never leaves a gap
    farMaterial.setFloat('uNearCut', Math.max(0, (rings.mid - 0.6) * TILE));
  }
  syncFarCut();

  /* ---- one mesh per species, buffers repacked from resident tiles -------- */
  const species = {};
  for (const def of SPECIES) {
    const mesh = speciesMesh(BABYLON, scene, field, shaders, def);
    mesh.thinInstanceCount = 0;
    species[def.name] = { def, mesh, matrices: null, tints: null, cap: 0, live: 0 };
  }

  const grass = {
    mesh: tuftMesh(BABYLON, scene, field, 6),
    matrices: null, tints: null, cap: 0, live: 0,
  };
  grass.mesh.material = grassMaterial(BABYLON, scene, shaders);
  grass.mesh.isPickable = false;
  grass.mesh.thinInstanceCount = 0;

  /* Colliders live and die with their tile, so obstacle collision inherits the
     streaming world's lifetime instead of becoming a second thing that leaks. */
  const colliders = opts.colliders || createColliders();

  const tiles = new Map();            // key -> tile
  const queue = [];                   // tiles waiting for work
  let repackNeeded = false;
  let built = 0, disposed = 0;

  const key = (i, j) => i + ',' + j;
  const LIM = WORLD.halfExtent;
  const IMIN = Math.floor(-LIM / TILE), IMAX = Math.ceil(LIM / TILE);

  /* ---- build stages ------------------------------------------------------ */

  function stageHeights(t) {
    const seg = t.lod === 0 ? TILE : TILE / 4;      // 1 m/quad near, 4 m mid
    const r = buildTerrainTile(BABYLON, scene, field, groundMat, {
      x0: t.x0, z0: t.z0, size: TILE, seg,
      name: `tile_${t.i}_${t.j}`, pool, skirt: t.lod === 0 ? 2.0 : 4.0,
    });
    t.mesh = r.mesh;
    t.heights = r.heights;
    t.NA = r.NA;
    t.step = r.step;
    t.size = TILE;

    /* The tile's climate at its own centre. Biomes blend over hundreds of
       metres, so one sample tells you what this 64 m square is — and that is
       enough to skip whole species outright. Without this gate a desert tile
       still pays full rejection sampling for pines and reeds and finds none,
       which was most of the placement cost. */
    const mx = t.x0 + TILE / 2, mz = t.z0 + TILE / 2;
    t.hCentre = field.heightAt(mx, mz);
    t.moistCentre = field.moistureAt(mx, mz);
    t.w = field.climate.climateAt(mx, mz, t.hCentre, field.inlandOf(mx, mz), t.moistCentre);
  }

  function stageFlora(t) {
    const scale = (t.lod === 0 ? density.near : density.mid) * floraScale;
    t.species = {};
    for (const def of SPECIES) {
      if (t.lod !== 0 && def.nearOnly) continue;

      // ask for roughly what this ground can actually supply
      const p0 = def.rule.pick(t.w, t.hCentre, 0, t.moistCentre);
      if (p0 < 0.03) continue;
      const n = Math.round(def.perTile * scale * Math.min(1, p0 * 1.5));
      if (n <= 0) continue;

      const rng = makeRNG(t.seed + def.rngSalt);
      const spots = tileScatter(field, t, rng, n, def.rule);
      if (!spots.length) continue;

      const M = pool.take(spots.length * 16);
      const T = pool.take(spots.length * 3);
      def.fill(BABYLON, spots, rng, M, T, field);
      t.species[def.name] = { M, T, n: spots.length };

      /* The collider is free here: the translation is already in the matrix and
         the radius scales with the instance. Only species that declare a trunk
         radius block — grass and reeds are brushed through. */
      if (def.collide) {
        const ck = key(t.i, t.j);
        for (let i = 0; i < spots.length; i++) {
          const o = i * 16;
          // mean horizontal scale, so a big tree blocks more than a sapling
          const sx = Math.hypot(M[o], M[o + 1], M[o + 2]);
          const sz = Math.hypot(M[o + 8], M[o + 9], M[o + 10]);
          colliders.add(ck, M[o + 12], M[o + 14], def.collide * (sx + sz) * 0.5);
        }
        t.hasColliders = true;
      }
    }
  }

  function stageGrass(t) {
    if (t.lod !== 0 || grassScale <= 0) return;
    const p0 = GRASS_RULE.pick(t.w);
    if (p0 < 0.04) return;
    const n = Math.round((opts.grassPerTile || 2600) * grassScale * Math.min(1, p0 * 1.4));
    if (n <= 0) return;
    const rng = makeRNG(t.seed + 99173);
    const spots = tileScatter(field, t, rng, n, GRASS_RULE);
    if (!spots.length) return;
    const M = pool.take(spots.length * 16);
    const T = pool.take(spots.length * 3);
    fillGrass(BABYLON, spots, rng, M, T, field);
    t.grass = { M, T, n: spots.length };
  }

  const STAGES = [stageHeights, stageFlora, stageGrass];

  /* ---- residency --------------------------------------------------------- */

  function want(cx, cz) {
    const ci = Math.floor(cx / TILE), cj = Math.floor(cz / TILE);
    const set = new Map();
    for (let dj = -rings.mid; dj <= rings.mid; dj++) {
      for (let di = -rings.mid; di <= rings.mid; di++) {
        const i = ci + di, j = cj + dj;
        if (i < IMIN || i > IMAX || j < IMIN || j > IMAX) continue;
        const d = Math.max(Math.abs(di), Math.abs(dj));
        if (d > rings.mid) continue;
        set.set(key(i, j), { i, j, lod: d <= rings.near ? 0 : 1, d });
      }
    }
    return set;
  }

  /**
   * Free everything a tile owns. Order matters: the GPU buffers go first, then
   * the CPU arrays go back to the pool, then every reference is nulled so that
   * nothing keeps the tile alive after it leaves the map.
   */
  function disposeTile(t) {
    if (t.hasColliders) { colliders.removeOwner(key(t.i, t.j)); t.hasColliders = false; }
    if (t.mesh) { t.mesh.dispose(false, true); t.mesh = null; }
    if (t.heights) { pool.give(t.heights); t.heights = null; }
    if (t.species) {
      for (const k in t.species) {
        pool.give(t.species[k].M);
        pool.give(t.species[k].T);
      }
      t.species = null;
    }
    if (t.grass) { pool.give(t.grass.M); pool.give(t.grass.T); t.grass = null; }
    t.done = false;
    disposed++;
  }

  /* ---- repacking the species buffers ------------------------------------- */

  function ensureCap(slot, n) {
    if (slot.cap >= n) return;
    const cap = Math.max(64, Math.ceil(n * 1.35));
    slot.matrices = new Float32Array(cap * 16);
    slot.tints = new Float32Array(cap * 3);
    slot.cap = cap;
    slot.dirtyBuffers = true;
  }

  function repack() {
    repackNeeded = false;

    for (const name in species) {
      const slot = species[name];
      let total = 0;
      for (const t of tiles.values()) {
        if (t.done && t.species && t.species[name]) total += t.species[name].n;
      }
      ensureCap(slot, total);
      let off = 0;
      for (const t of tiles.values()) {
        if (!t.done || !t.species || !t.species[name]) continue;
        const s = t.species[name];
        slot.matrices.set(s.M.subarray(0, s.n * 16), off * 16);
        slot.tints.set(s.T.subarray(0, s.n * 3), off * 3);
        off += s.n;
      }
      slot.live = total;
      applySlot(slot);
    }

    let gTotal = 0;
    for (const t of tiles.values()) if (t.done && t.grass) gTotal += t.grass.n;
    ensureCap(grass, gTotal);
    let goff = 0;
    for (const t of tiles.values()) {
      if (!t.done || !t.grass) continue;
      grass.matrices.set(t.grass.M.subarray(0, t.grass.n * 16), goff * 16);
      grass.tints.set(t.grass.T.subarray(0, t.grass.n * 3), goff * 3);
      goff += t.grass.n;
    }
    grass.live = gTotal;
    applySlot(grass);
  }

  function applySlot(slot) {
    if (!slot.matrices || slot.live === 0) {
      slot.mesh.thinInstanceCount = 0;
      return;
    }
    if (slot.dirtyBuffers || !slot.bound) {
      slot.mesh.thinInstanceSetBuffer('matrix', slot.matrices, 16, true);
      slot.mesh.thinInstanceSetBuffer('aTint', slot.tints, 3, true);
      slot.bound = true;
      slot.dirtyBuffers = false;
    } else {
      slot.mesh.thinInstanceBufferUpdated('matrix');
      slot.mesh.thinInstanceBufferUpdated('aTint');
    }
    slot.mesh.thinInstanceCount = slot.live;
    slot.mesh.thinInstanceRefreshBoundingInfo(false);
  }

  /* ---- the frame --------------------------------------------------------- */

  let lastKeyI = NaN, lastKeyJ = NaN;

  function update(cx, cz, budgetMs) {
    const ci = Math.floor(cx / TILE), cj = Math.floor(cz / TILE);

    if (ci !== lastKeyI || cj !== lastKeyJ) {
      lastKeyI = ci; lastKeyJ = cj;
      const wanted = want(cx, cz);

      // evict everything outside the ring
      for (const [k, t] of tiles) {
        if (!wanted.has(k)) {
          disposeTile(t);
          tiles.delete(k);
          repackNeeded = true;
        }
      }
      // admit everything new, and re-admit anything whose LOD changed
      for (const [k, w] of wanted) {
        const have = tiles.get(k);
        if (have) {
          if (have.lod !== w.lod) { disposeTile(have); tiles.delete(k); repackNeeded = true; }
          else continue;
        }
        const t = {
          i: w.i, j: w.j, lod: w.lod, d: w.d,
          x0: w.i * TILE, z0: w.j * TILE,
          seed: field.seed + w.i * 73856093 + w.j * 19349663,
          stage: 0, done: false,
          mesh: null, heights: null, species: null, grass: null,
        };
        tiles.set(k, t);
      }
      // nearest first: what is under your feet matters more than the horizon
      queue.length = 0;
      for (const t of tiles.values()) if (!t.done) queue.push(t);
      queue.sort((a, b) => a.d - b.d);
    }

    // spend the frame's budget
    const budget = budgetMs == null ? 4 : budgetMs;
    const t0 = performance.now();
    while (queue.length && performance.now() - t0 < budget) {
      const t = queue[0];
      if (!tiles.has(key(t.i, t.j))) { queue.shift(); continue; }
      STAGES[t.stage](t);
      t.stage++;
      if (t.stage >= STAGES.length) {
        t.done = true;
        built++;
        repackNeeded = true;
        queue.shift();
      }
    }

    if (repackNeeded) repack();
  }

  /**
   * Build right now, ignoring the frame budget.
   *
   * `maxRing` limits how far out to go. Boot passes the NEAR ring only: the
   * player has to be standing on real ground before the veil lifts, but the
   * middle distance can arrive over the next few seconds under the budget,
   * which is the entire point of streaming. Tests pass nothing and get the lot,
   * because a screenshot of a half-built ring is a screenshot of a bug that
   * isn't there.
   */
  function prime(cx, cz, maxRing) {
    lastKeyI = NaN;
    update(cx, cz, 0);
    const limit = maxRing == null ? Infinity : maxRing;
    let guard = 0;
    while (queue.length && guard++ < 20000) {
      if (queue[0].d > limit) break;          // the queue is sorted nearest-first
      const t = queue[0];
      if (!tiles.has(key(t.i, t.j))) { queue.shift(); continue; }
      STAGES[t.stage](t);
      t.stage++;
      if (t.stage >= STAGES.length) { t.done = true; built++; repackNeeded = true; queue.shift(); }
    }
    repack();
  }

  function setQuality(q) {
    let changed = false;
    if (q.nearRings != null && q.nearRings !== rings.near) { rings.near = q.nearRings; changed = true; }
    if (q.midRings != null && q.midRings !== rings.mid) { rings.mid = q.midRings; changed = true; }
    if (q.grassScale != null && q.grassScale !== grassScale) { grassScale = q.grassScale; changed = true; }
    if (q.floraScale != null && q.floraScale !== floraScale) { floraScale = q.floraScale; changed = true; }
    if (changed) {
      syncFarCut();
      for (const [k, t] of tiles) { disposeTile(t); tiles.delete(k); }
      queue.length = 0;
      lastKeyI = NaN;
      repackNeeded = true;
    }
    return changed;
  }

  function mem() {
    const inst = {};
    let total = 0;
    for (const n in species) { inst[n] = species[n].live; total += species[n].live; }
    inst.grass = grass.live;
    total += grass.live;
    let resident = 0, pending = 0;
    for (const t of tiles.values()) { if (t.done) resident++; else pending++; }
    const p = pool.stats();
    return {
      tiles: tiles.size, resident, pending, queued: queue.length,
      built, disposed,
      instances: inst, totalInstances: total,
      colliders: colliders.count,
      pooledBytes: p.pooledBytes, poolBins: p.bins,
      poolRecycleRate: p.taken ? +(p.recycled / p.taken).toFixed(3) : 0,
      meshes: scene.meshes.length,
      vertices: scene.getTotalVertices(),
      heapMB: (performance.memory && performance.memory.usedJSHeapSize)
        ? +(performance.memory.usedJSHeapSize / 1048576).toFixed(1) : null,
    };
  }

  function dispose() {
    for (const [k, t] of tiles) { disposeTile(t); tiles.delete(k); }
    colliders.clear();
    for (const n in species) species[n].mesh.dispose(false, true);
    grass.mesh.dispose(false, true);
    far.mesh.dispose(false, true);
    pool.clear();
  }

  const mats = [groundMat, farMaterial, grass.mesh.material];
  for (const n in species) mats.push(species[n].mesh.material);

  return {
    update, prime, setQuality, mem, dispose,
    mats, far, species, grass, tiles, pool, colliders,
    get tileSize() { return TILE; },
    get rings() { return { ...rings }; },
    /** tests: the exact bytes a tile produced, for the determinism check */
    snapshot(i, j) {
      const t = tiles.get(key(i, j));
      if (!t || !t.done) return null;
      const out = { lod: t.lod, species: {} };
      for (const n in t.species) {
        const s = t.species[n];
        out.species[n] = { n: s.n, hash: hashFloats(s.M, s.n * 16) };
      }
      if (t.grass) out.grass = { n: t.grass.n, hash: hashFloats(t.grass.M, t.grass.n * 16) };
      return out;
    },
  };
}

/** FNV-ish hash over a float buffer — enough to prove two builds are identical. */
function hashFloats(a, n) {
  let h = 2166136261 >>> 0;
  const view = new Uint32Array(a.buffer, a.byteOffset, n);
  for (let i = 0; i < n; i++) {
    h ^= view[i];
    h = Math.imul(h, 16777619) >>> 0;
  }
  return h;
}

/* ==========================================================================
   Grass, per tile
   ========================================================================== */

const GRASS_RULE = {
  effort: 8, minY: 0.9, maxY: 150, maxSlope: 0.50,
  pick: (w) => clamp(
    w.meadow * 1.0 + w.marsh * 0.95 + w.forest * 0.55 +
    w.beach * 0.14 + w.desert * 0.07 - w.snow * 0.9 - w.rock * 0.6, 0, 1),
};

let grassTintNoise = null;

function fillGrass(BABYLON, spots, rng, M, T, field) {
  if (!grassTintNoise) grassTintNoise = makeNoise2D(field.seed + 8181);
  const m = BABYLON.Matrix.Identity();
  const sv = new BABYLON.Vector3(), pv = new BABYLON.Vector3();
  for (let i = 0; i < spots.length; i++) {
    const s = spots[i];
    const sc = 0.80 + rng() * 0.60;
    const hs = sc * lerp(0.76, 1.28, s.moist);
    sv.set(sc, hs, sc);
    pv.set(s.x, s.y - 0.06, s.z);
    BABYLON.Matrix.ComposeToRef(sv,
      BABYLON.Quaternion.RotationAxis(BABYLON.Axis.Y, rng() * Math.PI * 2), pv, m);
    m.copyToArray(M, i * 16);

    const drift = grassTintNoise(s.x * 0.013, s.z * 0.013) * 0.5 + 0.5;
    const w = s.w;
    const dry = clamp(clamp(1 - s.moist, 0, 1) * 0.6 + clamp(w.desert + w.beach, 0, 1) * 0.9, 0, 1);
    const deep = clamp(w.forest + w.marsh, 0, 1);
    T[i * 3 + 0] = lerp(lerp(0.19, 0.52, dry), 0.15, deep) * lerp(0.86, 1.12, drift);
    T[i * 3 + 1] = lerp(lerp(0.42, 0.49, dry), 0.33, deep) * lerp(0.88, 1.10, drift);
    T[i * 3 + 2] = lerp(lerp(0.16, 0.26, dry), 0.16, deep) * lerp(0.82, 1.14, drift);
  }
}
